const Zahir = {
  title: 'The Zahir: A Journey Through Obsession, Loss, and Liberation',
  content: [
    'I came to Paulo Coelho`s The Zahir during a season of personal turbulence, searching for meaning in the aftermath of something I could not quite name. The book found me at precisely the right moment, or perhaps I found it. Either way, this novel became a mirror reflecting parts of myself I had been afraid to examine too closely. I approached it as someone who has always been prone to intensity, who loves deeply and attaches fiercely, and who has often mistaken obsession for devotion.',
    'The heart of The Zahir is this compelling paradox: the narrator becomes so consumed with understanding his wife Esther`s departure that he becomes imprisoned by her absence. Every thought spirals back to her. He reads about other obsessions, collects stories, becomes a scholar of his own pain. And somewhere in those pages, I recognized myself—the countless hours spent replaying moments, analyzing words, building entire narratives around a single person or loss. What struck me most profoundly was Coelho`s unflinching exploration of how obsession masquerades as love. The book challenged me to see that my fixation says far more about my own incompleteness than about love itself.',
    'As the novel progresses, the narrator begins to understand something revolutionary: that the Zahir, that which consumes our entire vision is not actually about the object of obsession. It is about what we are using that obsession to avoid: ourselves. This is the book`s central wisdom, and it transformed how I think about attachment and freedom. Letting go is not about stopping to love or care. It is about releasing the need to possess, understand, or control. The narrator`s gradual liberation comes not from finding Esther but from surrendering the compulsion to find her.',
    'One concept that particularly moved me was the idea of living between two rivers—between passion and tranquility, between risk and security. The narrator realizes that life is not meant to be stable or completely understood. We are meant to flow, to change, to sometimes not know where we are going. This shifted my entire perspective. I spent so much time trying to dam the rivers of my own emotions, to control their flow. But Coelho suggests that the full experience of being human means allowing ourselves to be moved, even dangerously so, while still maintaining our core sense of self.',
    'By the end, I realized The Zahir is not really about a marriage ending or a woman leaving. It is about the day we stop making someone else responsible for our happiness. It ia about the moment we accept that another person, no matter how loved, cannot fill the void inside us—nor should they be expected to. The narrator`s final freedom comes when he stops asking why Esther left and starts asking who he is when he is not defined by her absence.',
    'Weeks after finishing, certain truths from this book echo in my mind. Coelho writes with the precision of someone who has stared into the abyss of obsession and returned to tell the tale. This is not a comfortable book. It does not coddle. But it offers something more valuable than comfort: clarity. I am still extracting meaning from The Zahir, and every contemplation reveals new depths, new warnings, new wisdom. If you have ever loved too fiercely, held too tightly, or lost yourself in another person, this book will feel like a necessary conversation with an old friend who is not afraid to tell you the truth you need to hear.',
  ]
};

export default Zahir;
